---

- name: run the playbook tasks on the localhost
  hosts: localhost
  become: yes

  tasks:

  - name: create US English locale
    locale_gen:
      name: en_US.UTF-8
      state: present

  - name: apt update
    become: true
    apt:
      cache_valid_time: 86400
      update_cache: yes
      upgrade: full
