- hosts: all
  name: install terraform
  become: yes
  tasks:
  - name: add docker key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: add docker repo
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present
  - name: apt update
    become: true
    apt:
      cache_valid_time: 86400
      update_cache: yes
  - name: install docker
    apt: name=docker-ce state=present
  - name: add vagrant to docker group
    user:
      name: vagrant
      groups: docker
      state: present
